accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from accounts.views import LoginUserView, RegisterView, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='user_create'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('gallery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from gallery.views import (
    PhotoListView, PhotoDetailView,
    PhotoCreateView, PhotoUpdateView,
    PhotoDeleteView
)

app_name = 'gallery'

urlpatterns = [
    path('', PhotoListView.as_view(), name='photo_list'),
    path('photo/<int:pk>', PhotoDetailView.as_view(), name='photo_detail'),
    path('photo/add', PhotoCreateView.as_view(), name='photo_create'),
    path('photo/<int:pk>/edit', PhotoUpdateView.as_view(), name='photo_edit'),
    path('photo/<int:pk>/delete', PhotoDeleteView.as_view(), name='photo_delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.db import models


class Photo(models.Model):
    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='photo_images',
        verbose_name='Image',
        validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])]
    )
    title = models.CharField(max_length=100, verbose_name='Title')
    author = models.ForeignKey(
        to=get_user_model(),
        related_name='photos',
        on_delete=models.CASCADE,
        verbose_name='Author',
    )
    bookmarked_users = models.ManyToManyField(
        to=get_user_model(),
        related_name='bookmarked_photos',
        through='gallery.Bookmark',
        through_fields=('photo', 'user'),
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created')

    def __str__(self):
        return "{}. {} by {}".format(self.pk, self.title, self.author)


class Bookmark(models.Model):
    photo = models.ForeignKey(
        to='gallery.Photo', on_delete=models.CASCADE,
        related_name='photo_bookmarks', verbose_name='Photo'
    )
    user = models.ForeignKey(
        to=get_user_model(), on_delete=models.CASCADE,
        verbose_name='User', related_name='user_bookmarks'
    )

    class Meta:
        unique_together = ['user', 'photo']

    def __str__(self):
        return f'{self.user} bookmarks photo "{self.photo}"'

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms


class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput,
        label='Password',
        strip=False,
        required=True,
    )
    password_confirm = forms.CharField(
        widget=forms.PasswordInput,
        label='Repeat password',
        strip=False,
        required=True,
    )
    email = forms.EmailField(required=True, label='Email', widget=forms.EmailInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('The passwords are not the same')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'password',
            'password_confirm',
            'first_name',
            'email',
        ]

gallery/forms.py
from django import forms
from gallery.models import Photo, Bookmark


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'title']


class BookmarkForm(forms.ModelForm):
    class Meta:
        model = Bookmark
        exclude = ['user', 'photo']

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView

from accounts.forms import MyUserCreationForm


class LoginUserView(LoginView):
    template_name = 'accounts/registration/login.html'
    # redirect_authenticated_user = True


class RegisterView(CreateView):
    model = get_user_model()
    template_name = 'accounts/registration/user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:login')


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'accounts/user_detail.html'
    context_object_name = 'user_obj'

gallery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from gallery.forms import PhotoForm
from gallery.models import Photo


class PhotoListView(ListView):
    template_name = 'gallery/photo/photo_list.html'
    model = Photo
    context_object_name = 'photos'

    def get_queryset(self):
        return super().get_queryset().order_by('-created_at')


class PhotoDetailView(DetailView):
    template_name = 'gallery/photo/photo_detail.html'
    model = Photo
    context_object_name = 'photo'


class PhotoCreateView(LoginRequiredMixin, CreateView):
    template_name = 'gallery/photo/photo_create.html'
    model = Photo
    form_class = PhotoForm

    def form_valid(self, form):
        photo = form.save(commit=False)
        photo.author = self.request.user
        photo.save()
        self.object = photo
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('gallery:photo_detail', kwargs={'pk': self.object.pk})


class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'gallery/photo/photo_update.html'
    model = Photo
    form_class = PhotoForm
    permission_required = 'gallery.change_photo'

    def get_success_url(self):
        return reverse('gallery:photo_detail', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user


class PhotoDeleteView(PermissionRequiredMixin, DeleteView):
    model = Photo
    permission_required = 'gallery.delete_photo'

    def get_success_url(self):
        return reverse('gallery:photo_list')

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

templates/accounts/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 style="text-transform: capitalize">{{ user_obj.username }}'s account</h1>

    <div class="card mb-3" style="border: none">
        <div class="row g-0">
            <div class="card-body">
                    <h5 class="card-title">Username: {{ user_obj.username }}</h5>
                    <p class="card-text">Name: {{ user_obj.first_name }}</p>
                    <p class="card-text">Email: {{ user_obj.email }}</p>
                </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
{% include 'partial/common/menu.html' %}
<div class="container">
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.errors }}
        </div>
    {% endif %}
    {% if cart_empty_order_error %}
        <div class="alert alert-danger" role="alert">
            {{ cart_empty_order_error }}
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/3df35e8034.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/gallery/photo/photo_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'gallery:photo_create' %}" method="post" enctype="multipart/form-data">
    {% include 'partial/photo/photo_form.html' with btn_title='Add' %}
    </form>
{% endblock %}

templates/gallery/photo/photo_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="photo-container">
        <div class="card mb-3 post">
            <div class="card-header">
                <a href="{% url 'gallery:photo_detail' photo.pk %}">
                    <div class="image">
                        <img src="{{ photo.image.url }}" class="card-img-top" alt="...">
                    </div>
                </a>
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ photo.title }}</h4>
                <p class="card-text">by <a href="{% url 'accounts:user_detail' photo.author.pk %}"><span
                        class="username-text">{{ photo.author.username }}</span></a></p>
                {% if request.user.is_authenticated %}
                <div>
                    <button class="btn btn-bookmark" data-id="{{ photo.pk }}"
                        style="padding: 0">
                </button>
                </div>
                {% endif %}
                <small class="text-muted">{{ photo.created_at }}</small>
                <div class="card-footer">
                    {% if perms.gallery.change_photo or request.user == photo.author %}
                        <a href="{% url 'gallery:photo_edit' photo.pk %}" class="btn btn-primary">Edit</a>
                    {% endif %}
                    {% if perms.gallery.delete_photo or request.user == photo.author %}
                        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete
                        </button>
                        {% include 'partial/photo/delete_photo_modal.html' %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <h3 style="margin-top: 40px">Bookmarked users</h3>
    {% include 'partial/accounts/partial_user_list.html' with user_objects=photo.bookmarked_users.all %}
{% endblock %}

templates/gallery/photo/photo_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'partial/photo/partial_photo_list.html' %}
{% endblock %}

templates/gallery/photo/photo_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'gallery:photo_edit' photo.pk %}" method="post" enctype="multipart/form-data">
    {% include 'partial/photo/photo_form.html' with btn_title='Edit' %}
    </form>
{% endblock %}

templates/partial/accounts/partial_user_list.html
{% for usr in user_objects %}
        <div class="card mb-3" style="border: none">
            <div class="row g-0">
                <div class="col-md-5">
                    <div class="card-body">
                        <h5 class="card-title"><a
                                href="{% url 'accounts:user_detail' usr.pk %}"> {{ usr.username }}</a></h5>
                        <p class="card-text"><small class="text-muted">{{ usr.email }}</small></p>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <p>No users bookmarked</p>
    {% endfor %}

templates/partial/common/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'gallery:photo_list' %}">Main</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'gallery:photo_list' %}">Photos</a>
                </li>
            {% if request.user.is_authenticated %}
                   <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'gallery:photo_create' %}">Add
                        photo</a>
                </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item nav-link">
                        Hello, <a href="{% url 'accounts:user_detail' user.pk %}">{{ user.username }}</a>!
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="{% url 'accounts:logout' %}" id="btn-sing-out">Sign out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="
                                {% url 'accounts:login' %}">Sign in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/partial/photo/delete_photo_modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm removing</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure to remove this photo?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
                <form action="{% url 'gallery:photo_delete' photo.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/partial/photo/partial_photo_list.html
{% load static %}
<div class="photo-container">
    {% for photo in photos %}
        <div class="card mb-3 post">
            <div class="card-header">
                <a href="{% url 'gallery:photo_detail' photo.pk %}">
                    <div class="image">
                    <img src="{{ photo.image.url }}" class="card-img-top" alt="...">
                </div>
                </a>
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ photo.title }}</h4>
                <p class="card-text">by <a href="{% url 'accounts:user_detail' photo.author.pk %}"><span class="username-text">{{ photo.author.username }}</span></a></p>
                {% if request.user.is_authenticated %}
                <div>
                    <button class="btn btn-bookmark" data-id="{{ photo.pk }}"
                        style="padding: 0">
                </button>
                </div>
                {% endif %}
                <small class="text-muted">{{ photo.created_at }}</small>

            </div>
        </div>
    {% empty %}
        <p>Photos not found</p>
    {% endfor %}
</div>
{% if is_paginated %}
    {% include 'common/paginator.html' %}
{% endif %}

templates/partial/photo/photo_form.html
{% csrf_token %}
<div class="mb-3">
    <label for="title" class="form-label">{{ form.title.label }}</label>
    <input type="text" class="form-control" id="title" name="{{ form.title.name }}" value="{{ form.instance.title }}">
</div>
<div class="mb-3">
    <label for="image" class="form-label">{{ form.image.label }}</label>
    <input type="file" class="form-control" id="image" name="{{ form.image.name }}">
</div>
<button type="submit" class="btn btn-primary">{{ btn_title }}</button>